ARG BUILD_DATE=0
ARG COMMIT=0
ARG VERSION=unknown
ARG BINARY=prometheus

FROM golang:1.23 AS builder
ARG BINARY
RUN mkdir -p $GOPATH/pkg/mod $GOPATH/bin $GOPATH/src /${BINARY}
COPY . $GOPATH/src
WORKDIR $GOPATH/src

RUN CGO_ENABLED=0 make ${BINARY}

FROM debian:buster-slim
ARG BUILD_DATE
ARG VERSION
ARG BINARY

ENV WATTPILOT_HOST=""
ENV WATTPILOT_PWD=""
ENV WATTPILOT_LOG=Info

COPY --from=builder /go/src/${BINARY}/${BINARY} /image

ENTRYPOINT [ "/image" ]%
